# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wQ8tO4Pxls9Pf-dlEKmid_JhnNpeMWdw
"""

#Hacer un programa que cuente el número total de bumeranes de una lista de números enteros y muestre cada uno de ellos. 
#Un búmeran es una secuencia formada por 3 números seguidos, en la cual el primero y el último son iguales, y el segundo es diferente. Por ejemplo [5, 2, 5]. 
#En la lista [7, 2, 1, 2, 3, 3, 3, 4, 2, 4, 1, 8]  hay 2 bumeranes ([2, 1, 2] y [4, 2, 4]).

listaBum = [7, 2, 1, 2, 3, 3, 3, 4, 2, 4, 1, 8, 1, 2, 1]
contador = 0
for rec in range(len(listaBum)):
  if listaBum[rec] == listaBum[rec+2] and listaBum[rec] != listaBum[rec+1]:
    contador = contador+1
    print(listaBum[rec], listaBum[rec+1], listaBum[rec+2])
print("Total de bumeranes", contador)