"""agrego vehiculos.

Revision ID: 3161ae0c2c36
Revises: 8e7545be869a
Create Date: 2024-06-25 19:56:29.478304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3161ae0c2c36'
down_revision = '8e7545be869a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=30), nullable=False),
    sa.Column('cilindrada', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
