"""agrego vehiculos.

Revision ID: c4d500f055bb
Revises: 3161ae0c2c36
Create Date: 2024-06-25 20:03:46.393355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4d500f055bb'
down_revision = '3161ae0c2c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('cilindrada',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('cilindrada',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
